### PR TITLE
Add parent tile support

### PR DESCRIPTION
**Pull request by loicgasser**

### CODE REVIEW

**Comment by gjn** [comment]
LGTM.

Maybe add 2-3 more test cases of irregular pyramid (swiss).

**Comment by loicgasser** [comment]
Yes I will add a load of tests.
I need to handle some special cases that are not addressed yet.
Should come soon.

**Comment by loicgasser** [comment]
@ltclm @procrastinatio given that you will take over this project. Please have a look and let me know if you find anything suspicious or if somehting is not clear.

**Comment by ltclm** [comment]
great work @loicgasser !!
lgtm

**Review by ltclm — APPROVED** [review]

**Pull request merged**
